import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import { Oswald } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const courierPrime = Courier_Prime({ weight: '400', subsets: ["latin"] });
const oswald = Oswald({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} bg-surface-500 dark:bg-surface-dark-200`}>
        <NavBar />
        <main className="md:overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
