import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const courierPrime = Courier_Prime({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${courierPrime.className} bg-bg-weak`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
